/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -i generic-types.h -p automountinterface /home/ndr/projects/libsystemd-qt/dbus/introspection/org.freedesktop.systemd1.Automount.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef AUTOMOUNTINTERFACE_H_1364657298
#define AUTOMOUNTINTERFACE_H_1364657298

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "generic-types.h"

/*
 * Proxy class for interface org.freedesktop.systemd1.Automount
 */
class OrgFreedesktopSystemd1AutomountInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.systemd1.Automount"; }

public:
    OrgFreedesktopSystemd1AutomountInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopSystemd1AutomountInterface();

    Q_PROPERTY(uint DirectoryMode READ directoryMode)
    inline uint directoryMode() const
    { return qvariant_cast< uint >(property("DirectoryMode")); }

    Q_PROPERTY(QString Result READ result)
    inline QString result() const
    { return qvariant_cast< QString >(property("Result")); }

    Q_PROPERTY(QString Where READ where)
    inline QString where() const
    { return qvariant_cast< QString >(property("Where")); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
