/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -i generic-types.h -p hostname1interface /home/ndr/projects/libsystemd-qt/dbus/introspection/org.freedesktop.hostname1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "hostname1interface.h"

/*
 * Implementation of interface class OrgFreedesktopHostname1Interface
 */

OrgFreedesktopHostname1Interface::OrgFreedesktopHostname1Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopHostname1Interface::~OrgFreedesktopHostname1Interface()
{
}


#include "hostname1interface.moc"
