/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -i generic-types.h -p jobinterface /home/ndr/projects/libsystemd-qt/dbus/introspection/org.freedesktop.systemd1.Job.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef JOBINTERFACE_H_1365342323
#define JOBINTERFACE_H_1365342323

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "generic-types.h"

/*
 * Proxy class for interface org.freedesktop.systemd1.Job
 */
class OrgFreedesktopSystemd1JobInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.systemd1.Job"; }

public:
    OrgFreedesktopSystemd1JobInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopSystemd1JobInterface();

    Q_PROPERTY(uint Id READ id)
    inline uint id() const
    { return qvariant_cast< uint >(property("Id")); }

    Q_PROPERTY(QString JobType READ jobType)
    inline QString jobType() const
    { return qvariant_cast< QString >(property("JobType")); }

    Q_PROPERTY(QString State READ state)
    inline QString state() const
    { return qvariant_cast< QString >(property("State")); }

    Q_PROPERTY(JobDBusUnit Unit READ unit)
    inline JobDBusUnit unit() const
    { return qvariant_cast< JobDBusUnit >(property("Unit")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Cancel()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Cancel"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
