/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -i generic-types.h -p timedate1interface /home/ndr/projects/libsystemd-qt/dbus/introspection/org.freedesktop.timedate1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "timedate1interface.h"

/*
 * Implementation of interface class OrgFreedesktopTimedate1Interface
 */

OrgFreedesktopTimedate1Interface::OrgFreedesktopTimedate1Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopTimedate1Interface::~OrgFreedesktopTimedate1Interface()
{
}


#include "timedate1interface.moc"
